spring:
  datasource:
    url: jdbc:h2:mem:maindb
#    url: jdbc:postgresql://192.168.77.138/hw13
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
#      schema-locations: schema.sql
#      data-locations: data.sql

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect


  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8888